# Generated by Django 3.2.12 on 2022-09-21 11:27

import Basic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=12)),
                ('lastname', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.BooleanField()),
                ('password', models.CharField(max_length=12, validators=[Basic.models.lenpassword])),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
