# Generated by Django 4.1.1 on 2022-09-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0003_alter_userregister_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='gender',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
