# Generated by Django 4.1.1 on 2022-09-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0004_alter_userregister_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
